let array = [9, 9, 9];

// for in loops over enumerable property names of an object
for (let i in array) {
  console.log(i); // "0", "1", "2",
}

// for of does use an object-specific iterator and loops over the values generated by that
for (let i of array) {
  console.log(i); // "9", "9", "9"
}
